Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to

compute the mean and variance of the elements present in the
array.

Comment what the mean and variance of sample represents.

In [1]:
import numpy as np

def compute_mean_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

# Example vector creation
N = 10  # Define the dimensionality of the vector
sample_vector = np.random.rand(1, N)  # Creating a random vector of shape 1xN

# Compute mean and variance
mean, variance = compute_mean_variance(sample_vector)

print("Sample Vector:", sample_vector)
print("Mean:", mean)
print("Variance:", variance)

Sample Vector: [[0.57034922 0.63237441 0.4004435  0.38925018 0.33535989 0.50476013
  0.80074523 0.83330286 0.21956558 0.88017   ]]
Mean: 0.5566321003385802
Variance: 0.04644172732616709


Create two vectors each of dimension 1XM each representing N-
dimensional feature vector of a sample. Write a program to

compute the Covariance between them.

Comment what Covariance between two vectors represents.

In [2]:
import numpy as np

def compute_covariance(vector1, vector2):
    covariance_matrix = np.cov(vector1, vector2)
    covariance = covariance_matrix[0, 1]  # Extracting the covariance value from the covariance matrix
    return covariance

# Example vectors creation
M = 5  # Define the dimensionality of the vectors
sample_vector1 = np.random.rand(1, M)  # Creating a random vector of shape 1xM
sample_vector2 = np.random.rand(1, M)  # Creating another random vector of shape 1xM

# Compute covariance
covariance = compute_covariance(sample_vector1, sample_vector2)

print("Sample Vector 1:", sample_vector1)
print("Sample Vector 2:", sample_vector2)
print("Covariance between vectors:", covariance)

Sample Vector 1: [[0.25584087 0.65007892 0.67037579 0.86992284 0.94739697]]
Sample Vector 2: [[0.75823044 0.31094109 0.43522641 0.82019094 0.04253618]]
Covariance between vectors: -0.041233274381060454


Create two vectors each of dimension 1XN. Write a program to
compute the Correlation between them.

Comment what the Correlation represents.

In [3]:
import numpy as np

# Function to compute correlation
def compute_correlation(vector1, vector2):
    # Compute means
    mean1 = np.mean(vector1)
    mean2 = np.mean(vector2)
    
    # Compute standard deviations
    std_dev1 = np.std(vector1)
    std_dev2 = np.std(vector2)
    
    # Compute covariance
    covariance = np.mean((vector1 - mean1) * (vector2 - mean2))
    
    # Compute correlation
    correlation = covariance / (std_dev1 * std_dev2)
    
    return correlation

# Example vectors (replace these with your own vectors)
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([5, 4, 3, 2, 1])

# Compute correlation
corr = compute_correlation(vector1, vector2)
print("Correlation between the two vectors:", corr)


Correlation between the two vectors: -0.9999999999999998


Create a Matrix of MXN dimension representing the M-dimensional
feature vector for N number of samples i. e (i,j)th entry of the matrix
represents the ith feature of jth sample. Write a program to compute
the covariance matrix and correlation matrix. Comment on
takeaways from these matrixes.

In [4]:
import numpy as np

# Function to compute covariance matrix
def compute_covariance_matrix(matrix):
    return np.cov(matrix)

# Function to compute correlation matrix
def compute_correlation_matrix(matrix):
    return np.corrcoef(matrix)

# Example matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute covariance matrix
cov_matrix = compute_covariance_matrix(matrix)
print("Covariance Matrix:")
print(cov_matrix)

# Compute correlation matrix
corr_matrix = compute_correlation_matrix(matrix)
print("\nCorrelation Matrix:")
print(corr_matrix)


Covariance Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
